//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyz 
// TANGENT                  0   xyz         1     NONE  float       
// NORMAL                   0   xyzw        2     NONE  float       
// BLENDINDICES             0   xyzw        3     NONE   uint   xyzw
// BLENDWEIGHT              0   xyzw        4     NONE  float   xyzw
// TEXCOORD                 0   xy          5     NONE  float       
// COLOR                    0   xyzw        6     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// TEXCOORD                 4   x           0     NONE  float   x   
// SV_Position              0   xyzw        1      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[20], immediateIndexed
dcl_constantbuffer cb3[225], dynamicIndexed
dcl_input v0.xyz
dcl_input v3.xyzw
dcl_input v4.xyzw
dcl_output o0.x
dcl_output_siv o1.xyzw, position
dcl_temps 4
mad r0.xyz, v0.xyzx, cb0[13].xyzx, cb0[12].xyzx
imul null, r1.xyzw, v3.xyzw, l(3, 3, 3, 3)
mul r2.xyzw, v4.yyyy, cb3[r1.y + 1].xyzw
mad r2.xyzw, v4.xxxx, cb3[r1.x + 1].xyzw, r2.xyzw
mad r2.xyzw, v4.zzzz, cb3[r1.z + 1].xyzw, r2.xyzw
mad r2.xyzw, v4.wwww, cb3[r1.w + 1].xyzw, r2.xyzw
mov r0.w, l(1.000000)
dp4 r2.x, r0.xyzw, r2.xyzw
mul r2.xyzw, r2.xxxx, cb0[2].xyzw
mul r3.xyzw, v4.yyyy, cb3[r1.y + 0].xyzw
mad r3.xyzw, v4.xxxx, cb3[r1.x + 0].xyzw, r3.xyzw
mad r3.xyzw, v4.zzzz, cb3[r1.z + 0].xyzw, r3.xyzw
mad r3.xyzw, v4.wwww, cb3[r1.w + 0].xyzw, r3.xyzw
dp4 r3.x, r0.xyzw, r3.xyzw
mad r2.xyzw, cb0[1].xyzw, r3.xxxx, r2.xyzw
mul r3.xyzw, v4.yyyy, cb3[r1.y + 2].xyzw
mad r3.xyzw, v4.xxxx, cb3[r1.x + 2].xyzw, r3.xyzw
mad r3.xyzw, v4.zzzz, cb3[r1.z + 2].xyzw, r3.xyzw
mad r1.xyzw, v4.wwww, cb3[r1.w + 2].xyzw, r3.xyzw
dp4 r0.x, r0.xyzw, r1.xyzw
mad r0.xyzw, cb0[3].xyzw, r0.xxxx, r2.xyzw
add r0.xyzw, r0.xyzw, cb0[4].xyzw
mul r1.xyzw, r0.yyyy, cb0[16].xyzw
mad r1.xyzw, cb0[15].xyzw, r0.xxxx, r1.xyzw
mad r1.xyzw, cb0[17].xyzw, r0.zzzz, r1.xyzw
mad r0.xyzw, cb0[18].xyzw, r0.wwww, r1.xyzw
lt r1.x, r0.z, l(0.000000)
ne r1.y, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[19].z
and r1.x, r1.x, r1.y
movc r0.zw, r1.xxxx, l(0,0,0.000001,1.000000), r0.zzzw
mov o1.xyw, r0.xyxw
mad r0.x, r0.z, cb0[19].x, cb0[19].y
mul r0.x, r0.w, r0.x
mad o0.x, r0.x, cb0[19].x, cb0[19].y
mov o1.z, r0.x
ret 
// Approximately 0 instruction slots used
